### ISSUE TITLE
Complete testing of applications with updated upstream before merging to development.

### ISSUE THREAD

**Issue by DavidTheProgrammer** [CodeForAfrica/wazimap-ng#6]
Completed testing of updated backend with the following applications before the upstream can be merged to the staging branch.
This is a prerequisite for https://github.com/CodeForAfrica/wazimap-ng/issues/4 to close

- [x] ClimateMapped
~- [ ] PesaYetu~ This will be checked at a later date, it's configurations are less complicated than climatemapped so we expect it to work. We will not updated it without testing.

**Comment by satoru260** [comment]
The updated wazimap backend works with the climate mapped application as expected. The local application is referencing the local running backend at `HURUMAP_API_URL=http://localhost:8000`

![Image showing the homepage working](https://github.com/user-attachments/assets/3ae96441-853c-4949-82b2-f371c89b6abd)
Image showing the homepage working


![Image showing Temperature Variation data](https://github.com/user-attachments/assets/d9065a9f-39c2-4131-9432-3524add4ecb1)
Image showing Temperature Variation data


![Image showing Annual Temperature](https://github.com/user-attachments/assets/8c9e2794-0f3f-421e-9354-457c8073cd01)
Image showing Annual Temperature
